### PR TITLE
Fix Zlib end-of-stream detection.

### PR DESCRIPTION
**Pull request by TurboGit**
Add corresponding regression test.

For TC01-031.

### CODE REVIEW

**Review by anisimkov — COMMENTED** [review]
commit message told that it is the test, but I see the change in zlib.adb too.

**Comment by TurboGit** [comment]
No the first line is "Fix Zlib end-of-stream detection." and it the subject of this PR.

**Review by anisimkov — COMMENTED** [review]
Could you add some explanation of the problem to commit message.
As I can read from test, the failure does not happen when we remove few last bytes from compressed file. As I can understand it is bug too.

**Comment by TurboGit** [comment]
New version proposed.

I think this is correct and I don't see how some bytes could remain on the stream since the Read() on the stream did return with Last = 0 (no more data read). Also there is no regression. For sure you know this part of AWS better than me so if you have a better proposal let me know.

**Review by anisimkov — COMMENTED** [review]
I think need to add condition that there was no data in output
(No_Byte and then Last < Item_First and then V_Flush = Finish)

**Comment by TurboGit** [comment]
New version pushed, it is working using your proposal. Thanks.

**Review by anisimkov — APPROVED** [review]

**Pull request merged**
