### PR TITLE
Fix comment about NETLIB setup option

### PR DESCRIPTION
**Pull request by anisimkov**
MA31-001

### CODE REVIEW

**Comment by anisimkov** [comment]
Pascal, I think we should rebase before merge. I don't think we need "merge" commits.

**Comment by TurboGit** [comment]
Sure, for a single commit we can rebase.

**Comment by anisimkov** [comment]
If commits in same pull requrest but do not have functional relation it can be rebased too I think.

**Comment by TurboGit** [comment]
I agree too in this case. But most probably it should have been 2 PR instead of 1 from the beginning.

**Pull request merged**
