### PR TITLE
Fix websocket lock

### PR DESCRIPTION
**Pull request by TurboGit**
Please do not merge from GitHub. Thanks.

### CODE REVIEW

**Comment by TurboGit** [comment]
What do you mean by should not timeout at all?

**Comment by anisimkov** [comment]
I mean we should now wait any time inside of protected call for the output buffer availability. The right way is non-blocking send outside of protected operations. In this send we can detect that output buffer is full, in that case not sent data should be kept somewhere next to socket and the socket with the data should be placed to some special task waiting on set of such sockets for the output buffer availability. Way back to normal send is another story.

**Comment by TurboGit** [comment]
But this is not what is needed here. This is a blocking Send routine. This is important to ensure the same message is delivered to all waiting sockets. I'm not against a non blocking one, but this is not the semantic of this Send routine.

**Comment by anisimkov** [comment]
I propose to discuss it in slack chat, if you don't mind.

**Comment by anisimkov** [comment]
I removed check for Pre => Host'Length > 0; because empty host has meaning for server, it is bind to all available local addresses. Sometime we can bind to specific IPv4 address but additional bind going to be for all IPv6 addresses. I used this method on some regtest as I can remember.

**Comment by TurboGit** [comment]
> The check "Set.Length > 0" should be before wait and do not need to wait on empty set.

Indeed, we can even removed this condition. We cannot be there if Set.Length = 0.

**Pull request merged**
