### PR TITLE
po/client http2

### PR DESCRIPTION
**Pull request by TurboGit**
Not to be merged yet. Review welcomed.

### CODE REVIEW

**Comment by TurboGit** [comment]
@anisimkov : I have removed the "draft" status on this PR which should be ready for review. TIA.

**Review by anisimkov — CHANGES_REQUESTED** [review]
looks like typo in commit message "All are supported properly expept when there is attachments."

**Review by anisimkov — CHANGES_REQUESTED** [review]
<<Add routine Get_Content to retrieve the steamed headers. >> maybe stReamed ?

**Review by anisimkov — CHANGES_REQUESTED** [review]
I think no need to use Utils.Normalize_Lower in  src/http2/aws-http2-message.adb because it is only HTTP2 package, better to use just To_Lower here,

**Comment by TurboGit** [comment]
@anisimkov : new version with correction pushed.

**Pull request merged**
