### PR TITLE
Addressed warnings and compilation failures new with Ada 2012

### PR DESCRIPTION
**Pull request by plestedr**
Addressed warnings and failures noted during compilation under Ada 2012

### CODE REVIEW

**Comment by TurboGit** [comment]
Can you rebase on master please? I don't want to get the "Merge branch" in between of this PR. Also "Routine maintenance" is a bit generic.

**Comment by plestedr** [comment]
Not sure why it did that, I'll start with a fresh fork of the master.

**Comment by plestedr** [comment]
Cancelled to remove a conflict with a previous merge.

**Comment by TurboGit** [comment]
You don't have to close this PR. Just force push the new branch in this repository.

**Comment by plestedr** [comment]
OK. I am stuck here. This pull has 4 commits; the first one was already merged a few weeks ago, the second appears to be an artifact from synchronizing my fork with the master. Neither of those should be in this pull request. 

The third and fourth commits are the only ones I want to keep. I read the git documentation but I don't see a way to fix this pull request short of killing it and starting again. Can you point me to some help files that will explain? Very much a novice with git.

**Pull request closed without merging**
